import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "p-10"}>
        {children}
        <Link
          href={"https://chaicode.com/"}
          className=" fixed bottom-4 right-4 p-10"
        >
          <Image src="/logo.svg" alt="Logo" width={100} height={100} />
        </Link>
      </body>
    </html>
  );
}
